# Generated by Django 4.0.4 on 2022-06-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('total_score', models.FloatField(default=0.0)),
                ('problems_solved', models.TextField(default='')),
            ],
        ),
    ]
