# Generated by Django 4.0.4 on 2022-06-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
