# Generated by Django 4.0.4 on 2022-06-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_problemlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemlist',
            name='problem_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
