# Generated by Django 4.0.4 on 2022-06-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_problemlist_problem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(default='', max_length=250)),
                ('description', models.CharField(max_length=5000)),
                ('difficulty', models.IntegerField(default=1)),
                ('tags', models.CharField(max_length=250)),
                ('score', models.IntegerField(default=50)),
                ('solved_by', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='ProblemList',
        ),
    ]
