# Generated by Django 4.0.4 on 2022-06-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_problems_delete_problemlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=5000)),
                ('difficulty', models.IntegerField(default=1)),
                ('tags', models.CharField(max_length=250)),
                ('score', models.IntegerField(default=50)),
                ('solved_by', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Problems',
        ),
    ]
