# Generated by Django 4.0.4 on 2022-06-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_problems_delete_problemslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problems',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
